<?php
namespace Vanqard\Valideer\Rule;

use Vanqard\Valideer\DataField;

/**
 * Base class for validator rule instances
 *
 *
 * Class AbstractRule
 * @package Vanqard\Valideer\Rule
 */
abstract class AbstractRule implements RuleInterface
{
    /**
     * @var string
     */
    public static $errorMessage = "Rule %s generic error message";

    /**
     * @var string
     */
    protected $currentCustomErrorMessage;

    /**
     * @var array
     */
    protected $fields = [];

    /**
     * @var array
     */
    protected $errors = [];

    /**
     * Add a data object field to this validator
     *
     * @param DataField $field
     * @param array $params
     * @param string|null $messageOverride Optional custom message
     */
    public function addField(DataField $field, array $params = [], $messageOverride = null)
    {
        $fieldName = $field->getName();
        $this->fields[$fieldName] = [
            'field' => $field,
            'params' => $params,
            'msg' => (!is_null($messageOverride)) ?
                $messageOverride :
                static::$errorMessage
        ];
    }

    /**
     * Add an error message for the provided field
     *
     * @param $fieldName
     * @param $msg
     */
    public function addError($fieldName, $msg)
    {
        $this->errors[$fieldName] = $msg;
    }

    /**
     * Get the array of all errors found by this validator
     *
     * @return array
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Entry method to the validation process. This abstract
     * will apply the interface's 'isValid()' method to each of the
     * fields that have been added to this validator.
     *
     * @return void
     */
    public function validate()
    {
        foreach ($this->fields as $fieldName => $fieldSpec) {
            extract($fieldSpec);

            $this->currentCustomErrorMessage = $msg;

            if (!$this->isValid($field, $params)) {
                $field->addToAttr('errors', $this->getErrorMessage());
            }

            // Reset error message
            $this->currentCustomErrorMessage = null;
        }
    }

    /**
     * Helper method to collect the appropriate error message for the current field, which will
     * either be a custom error message supplied when addField was invoked, or the generic error message
     * generated by a particular rule instance.
     *
     * @return string $errorMessage
     */
    protected function getErrorMessage()
    {
        if (is_null($this->currentCustomErrorMessage)) {
            $this->currentCustomErrorMessage = sprintf(static::$errorMessage, get_class($this));
        }

        return $this->currentCustomErrorMessage;
    }

    /**
     * Abstract isValid method that all rule instances must support
     *
     * @param Datafield $field
     * @param array $params - additional validator params
     * @return boolean
     */
    abstract public function isValid(DataField $field, array $params = []);
}
